// ui/src/lib/components/StatCard.svelte
<script>
  let { label, value, sub = '', children } = $props();
</script>

<div class="rounded-lg border border-border bg-card p-4 text-card-foreground shadow-sm">
  <div class="flex items-start justify-between gap-2">
    <div class="min-w-0">
      <p class="text-xs font-medium text-muted-foreground">{label}</p>
      <p class="mt-1 truncate text-2xl font-semibold tracking-tight tabular-nums">{value}</p>
      {#if sub}
        <p class="mt-0.5 truncate text-xs text-muted-foreground">{sub}</p>
      {/if}
    </div>
    {@render children?.()}
  </div>
</div>

// ui/src/components/stat-card.tsx
import type { LucideIcon } from 'lucide-react';
import type { ReactNode } from 'react';
import { Card } from '@/components/ui/card';
import { cn } from '@/lib/utils';

export function StatCard({
  label,
  value,
  sub,
  icon: Icon,
  tone = 'default',
  children,
}: {
  label: string;
  value: string;
  sub?: string;
  icon: LucideIcon;
  tone?: 'default' | 'danger' | 'success';
  children?: ReactNode;
}) {
  return (
    <Card className="gap-0 py-4">
      <div className="flex items-start justify-between gap-3 px-4">
        <div className="min-w-0">
          <div className="text-muted-foreground flex items-center gap-1.5 text-xs font-medium">
            <Icon className="size-3.5" />
            {label}
          </div>
          <div
            className={cn(
              'mt-1.5 truncate text-2xl font-semibold tracking-tight tabular-nums',
              tone === 'danger' && 'text-destructive',
              tone === 'success' && 'text-success',
            )}
          >
            {value}
          </div>
          {sub && <div className="text-muted-foreground mt-0.5 truncate text-xs">{sub}</div>}
        </div>
        {children}
      </div>
    </Card>
  );
}
